POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "title": "created with a put request",
  "content": "hello express server",
  "color": "note--turquoise",
  "pinned": true,
  "trashed": false,
  "archived": false,
  "created": "2022-10-21T13:14:43.184Z",
  "edited": "2022-10-21T13:14:43.184Z"
}
